# Generated by Django 5.1.6 on 2025-02-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='Job',
            new_name='job',
        ),
    ]
