# Generated by Django 5.1.7 on 2025-03-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='first_Name',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='last_Name',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='password',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='username',
        ),
    ]
