# Generated by Django 5.1.7 on 2025-03-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_campususer_is_admin_alter_campususer_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campususer',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='campususer',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
