# Generated by Django 5.1.7 on 2025-03-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_campususer_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campususer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campususer',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
