# Generated by Django 5.1.7 on 2025-03-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_recruiter_submission_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hours_worked',
            field=models.IntegerField(default=0),
        ),
    ]
