# Generated by Django 5.1.6 on 2025-03-31 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_campususer_is_active_alter_campususer_is_staff_and_more'),
        ('master', '0005_alter_campususer_is_staff_and_more'),
    ]

    operations = [
    ]
