# Generated by Django 5.1.6 on 2025-03-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_merge_20250331_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='eligible_to_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campususer',
            name='email',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='campususer',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='campususer',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='campususer',
            name='user_type',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='campususer',
            name='username',
            field=models.CharField(default=None, max_length=64, null=True, unique=True),
        ),
    ]
