# Generated by Django 5.1.6 on 2025-04-11 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_remove_linemanager_student_linemanager_recruiter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='line_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.linemanager'),
        ),
    ]
