# Generated by Django 5.1.6 on 2025-04-11 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_alter_submission_line_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='line_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.linemanager'),
        ),
    ]
