"""
Django settings for campus1 project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# # Settings for deployment to Fuze.page
CSRF_TRUSTED_ORIGINS = ['https://edrms.fuze.page', 'https://campusjobs.fuze.page']
ALLOWED_HOSTS = ['edrms.fuze.page', 'campusjobs.fuze.page']
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    'rest_framework.authtoken',
    'rest_framework',
    'master',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_crontab',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'campus1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [BASE_DIR / 'master/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'campus1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# from sshtunnel import SSHTunnelForwarder
# 
# # Connect to a server using the ssh keys. See the sshtunnel documentation for using password authentication
# ssh_tunnel = SSHTunnelForwarder(
#     '195.201.102.136',
#     ssh_private_key='dbooserkey',
#     ssh_private_key_password='',
#     ssh_username='dbooser',
#     remote_bind_address=('localhost', 3306),
# )
# ssh_tunnel.start()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '127.0.0.1',
#         'PORT': ssh_tunnel.local_bind_port,
        'NAME': 'campoos',
        'USER': 'root',
        'PASSWORD': os.environ['MYSQUEALROOTPASSWORD'],
    },
    'shhtunnel_db': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '127.0.0.1',
#         'PORT': ssh_tunnel.local_bind_port, # For Fuze.page deployment, comment out this line
        'NAME': 'campoos',
        'USER': 'root',
        'PASSWORD': os.environ['MYSQUEALROOTPASSWORD'],
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CRONJOBS = [
    # Set all students' hours_worked to 0 every sunday
    ('0 0 * * 0', 'master.cron.resetStudentHours')
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = '/var/www/campusjobs/static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'homepage'
# LOGOUT_REDIRECT_URL = 'accounts/logged_out'

AUTH_USER_MODEL = 'master.CampusUser'


# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# # Settings for deployment to Fuze.page
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_PORT = 25
# EMAIL_USE_TLS = False
# EMAIL_HOST_USER = 'campusjobs'
# EMAIL_HOST_PASSWORD = 'str0ngpassword'
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
DEFAULT_FROM_EMAIL = 'Campus Jobs <campusjobs@fuze.page>'
